#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

ebegin "Updating projects.xml"
wget -nv -N -P "${repository_path}"/metadata https://api.gentoo.org/metastructure/projects.xml
eend "$?"
